services:
  mysql:
    image: mysql:8.4
    container_name: mysql-server

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campus
      MYSQL_USER: campus
      MYSQL_PASSWORD: campus123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2-data.sql

volumes:
  mysql_data:
